#!/usr/bin/env tsx
import 'dotenv/config';
import { exec } from 'child_process';
import { promisify } from 'util';
import { createConnection } from 'mysql2/promise';
import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';

const execAsync = promisify(exec);

// Color codes for terminal output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
};

const log = {
  info: (msg: string) => console.log(`${colors.blue}ℹ${colors.reset} ${msg}`),
  success: (msg: string) => console.log(`${colors.green}✓${colors.reset} ${msg}`),
  error: (msg: string) => console.log(`${colors.red}✗${colors.reset} ${msg}`),
  warning: (msg: string) => console.log(`${colors.yellow}⚠${colors.reset} ${msg}`),
  step: (msg: string) => console.log(`\n${colors.cyan}${colors.bright}→ ${msg}${colors.reset}`),
};

interface DatabaseConfig {
  host: string;
  port: number;
  user: string;
  password: string;
  database: string;
}

function parseDatabaseUrl(url: string): DatabaseConfig {
  // Parse mysql://user:password@host:port/database
  const regex = /mysql:\/\/([^:]+):([^@]+)@([^:]+):(\d+)\/(.+)/;
  const match = url.match(regex);

  if (!match) {
    throw new Error('Invalid DATABASE_URL format. Expected: mysql://user:password@host:port/database');
  }

  return {
    user: match[1],
    password: match[2],
    host: match[3],
    port: parseInt(match[4]),
    database: match[5],
  };
}

async function askQuestion(question: string, defaultValue: string = ''): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    const prompt = defaultValue ? `${question} [${defaultValue}]: ` : `${question}: `;
    rl.question(prompt, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultValue);
    });
  });
}

async function askPassword(question: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function generateJWTSecret(): string {
  return crypto.randomBytes(32).toString('hex');
}

async function checkEnvFileExists(): Promise<boolean> {
  return fs.existsSync(path.join(process.cwd(), '.env'));
}

async function createEnvFile(config: {
  databaseUrl: string;
  port: string;
  protocol: string;
  jwtSecret: string;
  authTime: string;
  steamApiKey: string;
  steamUserId: string;
  steamGridKey: string;
  ignoreBroadcast: string;
}): Promise<void> {
  const envContent = `# ================================
# LAN NEXUS SERVER - ENVIRONMENT VARIABLES
# ================================
# Generated by installer on ${new Date().toISOString()}

# ================================
# DATABASE CONFIGURATION
# ================================
DATABASE_URL=${config.databaseUrl}

# ================================
# SERVER CONFIGURATION
# ================================
PORT=${config.port}
PROTOCOL=${config.protocol}
NODE_ENV=development

# ================================
# JWT AUTHENTICATION
# ================================
JWT_SECRET=${config.jwtSecret}
AUTH_TIME=${config.authTime}

# ================================
# STEAM API
# ================================
STEAM_API_KEY=${config.steamApiKey}
STEAM_USER_ID=${config.steamUserId}

# ================================
# STEAMGRIDDB API
# ================================
STEAM_GRID_ID_KEY=${config.steamGridKey}

# ================================
# UDP BROADCAST CONFIGURATION
# ================================
IGNORE_BROADCAST=${config.ignoreBroadcast}
`;

  try {
    fs.writeFileSync(path.join(process.cwd(), '.env'), envContent);
    log.success('.env file created successfully');
  } catch (error: any) {
    throw new Error(`Failed to create .env file: ${error.message}`);
  }
}

async function configureEnvironment(): Promise<void> {
  console.log(`
${colors.bright}Environment Configuration${colors.reset}

Let's set up your environment variables. You'll need to obtain some API keys.
Don't worry, we'll provide links to help you get them!
`);

  const config: any = {};

  // Database configuration
  log.info(`${colors.bright}Database Configuration${colors.reset}`);
  console.log('Enter your MySQL/MariaDB connection details:\n');
  
  const dbHost = await askQuestion('Database host', 'localhost');
  const dbPort = await askQuestion('Database port', '3306');
  const dbUser = await askQuestion('Database username', 'root');
  const dbPassword = await askPassword('Database password: ');
  const dbName = await askQuestion('Database name', 'lan_nexus');
  
  config.databaseUrl = `mysql://${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${dbName}`;

  // Server configuration
  console.log('\n');
  log.info(`${colors.bright}Server Configuration${colors.reset}`);
  config.port = await askQuestion('Server port', '3000');
  config.protocol = await askQuestion('Protocol (http/https)', 'http');

  // JWT configuration
  console.log('\n');
  log.info(`${colors.bright}JWT Authentication${colors.reset}`);
  const useRandomJWT = await askQuestion('Generate random JWT secret? (Y/n)', 'Y');
  
  if (useRandomJWT.toLowerCase() === 'y' || useRandomJWT === '') {
    config.jwtSecret = generateJWTSecret();
    log.success('Generated secure JWT secret');
  } else {
    config.jwtSecret = await askQuestion('Enter JWT secret (min 32 chars)');
  }
  
  config.authTime = await askQuestion('Token expiration time (hours)', '24');

  // Steam API
  console.log('\n');
  log.info(`${colors.bright}Steam API Configuration${colors.reset}`);
  console.log(`${colors.cyan}Get your Steam API key: https://steamcommunity.com/dev/apikey${colors.reset}\n`);
  config.steamApiKey = await askQuestion('Steam API key');
  
  console.log(`\n${colors.cyan}Find your Steam ID: https://steamid.io/${colors.reset}\n`);
  config.steamUserId = await askQuestion('Steam User ID (17-digit SteamID64)');

  // SteamGridDB
  console.log('\n');
  log.info(`${colors.bright}SteamGridDB API Configuration${colors.reset}`);
  console.log(`${colors.cyan}Get your SteamGridDB API key:${colors.reset}`);
  console.log(`${colors.cyan}1. Create account: https://www.steamgriddb.com/${colors.reset}`);
  console.log(`${colors.cyan}2. Get API key: https://www.steamgriddb.com/profile/preferences/api${colors.reset}\n`);
  config.steamGridKey = await askQuestion('SteamGridDB API key');

  // Broadcast
  console.log('\n');
  log.info(`${colors.bright}Server Discovery${colors.reset}`);
  const enableBroadcast = await askQuestion('Enable UDP server discovery? (Y/n)', 'Y');
  config.ignoreBroadcast = (enableBroadcast.toLowerCase() === 'n') ? 'true' : 'false';

  // Create the .env file
  await createEnvFile(config);
  
  // Reload environment variables by re-reading the .env file
  const { config: dotenvConfig } = await import('dotenv');
  dotenvConfig({ override: true });
  
  log.info('Environment variables loaded successfully');
}

async function checkDatabaseConnection(config: DatabaseConfig): Promise<boolean> {
  try {
    const connection = await createConnection({
      host: config.host,
      port: config.port,
      user: config.user,
      password: config.password,
    });

    await connection.ping();
    await connection.end();
    return true;
  } catch (error) {
    return false;
  }
}

async function createDatabaseIfNotExists(config: DatabaseConfig): Promise<void> {
  try {
    const connection = await createConnection({
      host: config.host,
      port: config.port,
      user: config.user,
      password: config.password,
    });

    await connection.query(`CREATE DATABASE IF NOT EXISTS \`${config.database}\``);
    log.success(`Database '${config.database}' is ready`);
    await connection.end();
  } catch (error: any) {
    throw new Error(`Failed to create database: ${error.message}`);
  }
}

async function runMigrations(): Promise<void> {
  try {
    log.info('Generating migration files...');
    const { stdout: genStdout, stderr: genStderr } = await execAsync('npm run generate');
    if (genStdout) console.log(genStdout);
    if (genStderr && !genStderr.includes('Warning')) console.error(genStderr);

    log.info('Running database migrations...');
    const { stdout: migStdout, stderr: migStderr } = await execAsync('npm run migrate');
    if (migStdout) console.log(migStdout);
    if (migStderr && !migStderr.includes('Warning')) console.error(migStderr);

    log.success('Database migrations completed successfully');
  } catch (error: any) {
    throw new Error(`Migration failed: ${error.message}`);
  }
}

async function checkEnvironmentVariables(): Promise<boolean> {
  const requiredVars = [
    'DATABASE_URL',
    'STEAM_API_KEY',
    'STEAM_GRID_ID_KEY',
  ];

  const missing: string[] = [];

  for (const varName of requiredVars) {
    if (!process.env[varName]) {
      missing.push(varName);
    }
  }

  if (missing.length > 0) {
    log.warning('Missing required environment variables:');
    missing.forEach((varName) => {
      console.log(`  - ${varName}`);
    });
    return false;
  }

  log.success('All required environment variables are set');
  return true;
}

async function displayWelcome(): Promise<void> {
  console.log(`
${colors.cyan}${colors.bright}╔════════════════════════════════════════╗
║                                        ║
║      LAN Nexus Server Installer       ║
║                                        ║
╚════════════════════════════════════════╝${colors.reset}
`);
}

async function displaySummary(config: DatabaseConfig): Promise<void> {
  console.log(`
${colors.bright}Installation Summary:${colors.reset}
  Database Host: ${config.host}:${config.port}
  Database Name: ${config.database}
  Database User: ${config.user}
`);
}

async function main(): Promise<void> {
  try {
    await displayWelcome();

    // Step 0: Check if .env exists
    log.step('Step 1: Checking .env file');
    const envExists = await checkEnvFileExists();
    
    if (!envExists) {
      log.warning('.env file not found');
      const createEnv = await askQuestion('Would you like to create one now? (Y/n)', 'Y');
      
      if (createEnv.toLowerCase() === 'y' || createEnv === '') {
        await configureEnvironment();
      } else {
        log.error('Cannot continue without .env file');
        console.log('\nPlease create a .env file manually:');
        console.log('  1. Copy .env.example to .env');
        console.log('  2. Fill in your values');
        console.log('  3. Run this installer again');
        process.exit(1);
      }
    } else {
      log.success('.env file found');
    }

    // Step 1: Check environment variables
    log.step('Step 2: Validating environment variables');
    const varsValid = await checkEnvironmentVariables();
    
    if (!varsValid) {
      const reconfigure = await askQuestion('\nWould you like to reconfigure your .env file? (y/N)', 'N');
      
      if (reconfigure.toLowerCase() === 'y') {
        await configureEnvironment();
      } else {
        log.error('Cannot continue with missing environment variables');
        console.log('\nPlease update your .env file with the required values.');
        console.log('\nHelpful links:');
        console.log(`  Steam API Key: ${colors.cyan}https://steamcommunity.com/dev/apikey${colors.reset}`);
        console.log(`  SteamGridDB API: ${colors.cyan}https://www.steamgriddb.com/profile/preferences/api${colors.reset}`);
        console.log(`  Find Steam ID: ${colors.cyan}https://steamid.io/${colors.reset}`);
        process.exit(1);
      }
    }

    // Step 2: Parse database configuration
    log.step('Step 3: Parsing database configuration');
    const databaseUrl = process.env.DATABASE_URL!;
    const dbConfig = parseDatabaseUrl(databaseUrl);
    log.success('Database configuration parsed');

    // Step 3: Check database connection
    log.step('Step 4: Testing database connection');
    const isConnected = await checkDatabaseConnection(dbConfig);

    if (!isConnected) {
      log.error('Cannot connect to database server');
      log.warning('Please ensure your MySQL server is running');
      log.info('If using Docker, run: docker-compose up -d db');
      process.exit(1);
    }
    log.success('Database server is accessible');

    // Step 4: Create database if it doesn't exist
    log.step('Step 5: Setting up database');
    await createDatabaseIfNotExists(dbConfig);

    // Step 5: Display summary and confirm
    await displaySummary(dbConfig);
    
    const answer = await askQuestion(`\n${colors.yellow}Proceed with database migration? (y/N): ${colors.reset}`);
    
    if (answer.toLowerCase() !== 'y' && answer.toLowerCase() !== 'yes') {
      log.warning('Installation cancelled by user');
      process.exit(0);
    }

    // Step 6: Run migrations
    log.step('Step 6: Running database migrations');
    await runMigrations();

    // Success!
    console.log(`
${colors.green}${colors.bright}╔════════════════════════════════════════╗
║                                        ║
║    Installation completed successfully! ║
║                                        ║
╚════════════════════════════════════════╝${colors.reset}

${colors.bright}Next steps:${colors.reset}

  1. Start the application:
     ${colors.cyan}npm run dev${colors.reset}

  2. Access the application at:
     ${colors.cyan}http://localhost:${process.env.PORT || 3000}${colors.reset}

  3. Complete the first-time setup to create your admin account

${colors.bright}Additional commands:${colors.reset}

  • View database:  ${colors.cyan}npm run studio${colors.reset}
  • Production build: ${colors.cyan}npm run build${colors.reset}

${colors.yellow}Need help? Check the README.md file${colors.reset}
`);

  } catch (error: any) {
    log.error(`Installation failed: ${error.message}`);
    console.error('\nFull error:', error);
    process.exit(1);
  }
}

// Run the installer
main();